# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_calculator = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calculator.setGeometry(QtCore.QRect(30, 30, 112, 32))
        self.btn_calculator.setObjectName("btn_calculator")
        self.btn_color = QtWidgets.QPushButton(self.centralwidget)
        self.btn_color.setGeometry(QtCore.QRect(180, 30, 112, 32))
        self.btn_color.setObjectName("btn_color")
        self.btn_dataset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dataset.setGeometry(QtCore.QRect(340, 30, 112, 32))
        self.btn_dataset.setObjectName("btn_dataset")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "常用软件集合"))
        self.btn_calculator.setText(_translate("mainWindow", "计算器"))
        self.btn_color.setText(_translate("mainWindow", "颜色提取"))
        self.btn_dataset.setText(_translate("mainWindow", "数据库连接"))
